Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    config.vm.network :forwarded_port, host: 3306, guest: 3306
    config.vm.network :forwarded_port, host: 8080, guest: 8080
    config.vm.network :forwarded_port, host: 9000, guest: 9000
    config.vm.network "private_network", ip: "192.168.33.10"
    web.ssh.insert_key = true
    web.vm.synced_folder '.', '/vagrant'

    web.vm.provision :shell, :path => "install-app.sh"

    web.vm.provider :virtualbox do |vb|
        vb.gui = true
        # Use VBoxManage to customize the VM. For example to change memory:
        # vb.customize ["modifyvm", :id, "--name", "zosia-hania"]
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--vram", 64]
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
        vb.customize ['modifyvm', :id, '--draganddrop', 'bidirectional']
    end
  end
    
  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = "mysql57"
    db.vm.provision "shell", path: "install-db.sh"
    
    db.vm.define "mysql57" do |mysql57|
    end
  end

end