apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f app.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  selector:
    matchLabels:
      io.kompose.service: app
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f app.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xmx512m -Xms256m
        - name: SLEEP
          value: "30"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/jhipstersampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
        - name: SPRING_PROFILES_ACTIVE
          value: prod,swagger
        image: hvvka/twwo-app
        name: app
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
