Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.network "private_network", ip: "192.168.33.10"
    web.ssh.insert_key = true
    web.vm.synced_folder '.', '/vagrant'

    web.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook-web.yml"
      ansible.become = true
      ansible.verbose = "vvv"
    end

    web.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "run-jar.yml"
      run: "always"
    end

    web.vm.provider :virtualbox do |vb|
        vb.gui = true
        # Use VBoxManage to customize the VM. For example to change memory:
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--vram", 64]
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
        vb.customize ['modifyvm', :id, '--draganddrop', 'bidirectional']
    end
  end
    
  config.vm.define "db" do |db|
    db.vm.box = "hashicorp/precise64"
    db.vm.network "private_network", ip: "192.168.33.11"

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook-db.yml"
      ansible.become = true
      ansible.verbose = "vvv"
    end
  end

end